# Generated by Django 3.0.5 on 2020-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_auto_20200504_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='place',
        ),
        migrations.AddField(
            model_name='status',
            name='direction',
            field=models.CharField(default='とまる', max_length=100),
        ),
    ]
