# Generated by Django 3.0.5 on 2020-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0003_auto_20200504_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='power',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='status',
            name='direction',
            field=models.CharField(default='front', max_length=100),
        ),
    ]
