# Generated by Django 3.0.6 on 2020-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelchair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='car',
            field=models.IntegerField(default=-1),
        ),
    ]
